project_id = "hquoczkfumtpolyomrlg"

[functions.send-reservation-email]
verify_jwt = false

[functions.generate-demo-data]
verify_jwt = false

[functions.send-credit-alert-email]
verify_jwt = false

[functions.daily-credit-alerts]
verify_jwt = false

[functions.send-credit-receipt]
verify_jwt = false
